version: '3.2'

services:
  myrabbitmq:
    build: ./pokedex-core/rabbitmq-service
    ports:
      - '5672:5672'
      - '15672:15672'

  pokemon-db:
    build: ./pokedex-core/pokemon-db
    ports:
      - '3306:3306'

  log-service:
    build: ./pokedex-core/log-service
    depends_on:
      - myrabbitmq
    environment:
      - WAIT_HOSTS=myrabbitmq:5672
      - WAIT_HOSTS_TIMEOUT=240
      - RABBITMQ_HOST=myrabbitmq

  pokemon-service:
    build: ./pokedex-core/pokemon-service
    ports:
      - '3000:3000'
    depends_on:
      - myrabbitmq
      - pokemon-db
    environment:
      - WAIT_HOSTS=myrabbitmq:5672,pokemon-db:3306
      - WAIT_HOSTS_TIMEOUT=240
      - DATABASE_HOST=pokemon-db
      - RABBITMQ_HOST=myrabbitmq
      - CLIENT_HOST=pokedex-ui
  
  pokedex-ui:
    build: ./pokedex-ui
    ports:
      - '8080:8080'
